spring:
    sql:
        init:
            mode: always
            schema-locations: classpath:schema-h2.sql
            data-locations: classpath:data-h2.sql
    datasource:
        url: ${POSTGRES_URL}
        driver-class-name: org.postgresql.Driver
        username: yusuf_db_user
        password: ${POSTGRES_PASS}
    jpa:
        hibernate:
            ddl-auto: none
    h2:
        console:
            enabled: true
            path: /h2-console

    security:
        user:
            name: admin
            password: secret123
            roles: USER

external:
    polygon:
        api_key: ${POLYGON_API_KEY}

influxdb:
    url: http://localhost:8086
    token: yusuf_token
    org: yusufu
    bucket: financedata2
