spring:
    security:
        user:
            name: admin
            password: secret123
            roles: USER
    datasource:
        url: someurl
        driver-class-name: org.postgresql.Driver
        username: yusuf_db_user
        password: sth
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: false
    sql:
      init:
          mode: always

external:
    polygon:
        api_key: keyhere

influxdb:
    url: http://localhost:8086
    token: yusuf_token
    org: yusufu
    bucket: test2


resilience4j:
    circuitbreaker:
        instances:
            polygon:
                failureRateThreshold: 50
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                waitDurationInOpenState: 60s
                permittedNumberOfCallsInHalfOpenState: 3
    retry:
        instances:
            polygon:
                maxAttempts: 3
                waitDuration: 15s
                retryExceptions:
                    - java.io.IOException
                    - org.springframework.web.client.HttpServerErrorException

# Custom cron expression for the scheduled task
polygon.data.collection.cron: "0 0 1 * * ?"

