spring:
    sql:
        init:
            mode: always
            schema-locations: classpath:schema-postgres.sql
            data-locations: classpath:data-postgres.sql
    datasource:
        url: ${POSTGRES_URL}
        driver-class-name: org.postgresql.Driver
        username: yusuf_db_user
        password: ${POSTGRES_PASS}
    jpa:
        hibernate:
            ddl-auto: validate
    h2:
        console:
            enabled: false
            path: /h2-console

    security:
        user:
            name: admin
            password: secret123
            roles: USER



influxdb:
    url: ${INFLUX_AWS_URL}
    token: ${INFLUXDB_AWS_TOKEN}
    org: Java-Spring-Trading-Advisor
    bucket: TICK-AWS
